service: serverless-websockets

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-central-1'}
  runtime: provided.al2
  apiGateway:
    shouldStartNameWithService: true
  environment:
    # Variables the app needs to operate
    APP_STAGE: ${opt:stage, self:provider.stage}
    APP_REGION: ${opt:region, self:provider.region}
    APP_API_ID: !Ref "HttpApi"
    APP_SQS_URL: !Ref "SQSWebhookQueue"
    APP_WS_API_ID: !Ref "WebsocketsApi"

    # Configure the Pusher protocol app ID, key and secret
    APP_ID: ${ssm:/serverless-websockets/app-id}
    APP_KEY: ${ssm:/serverless-websockets/app-key}
    APP_SECRET: ${ssm:/serverless-websockets/app-secret}

    # Set the webhook target (https url) and the events that should be sent, leave emtpy to disable
    APP_WEBHOOK_TARGET: ${ssm:/serverless-websockets/webhook-target}
    # All available events: channel_occupied,channel_vacated,member_added,member_removed,client_event
    # For more info see: https://pusher.com/docs/channels/server_api/webhooks
    # Set the value to a comma seperated string, for example: channel_occupied,channel_vacated,client_event
    APP_WEBHOOK_EVENTS: ${ssm:/serverless-websockets/webhook-events}

    # Configure the server to allow client events on authenticated channels
    APP_CLIENT_EVENTS: ${ssm:/serverless-websockets/client-events-enabled}

    # Deploy to /wave a example app using a presence channel
    APP_WAVE_EXAMPLE_ENABLED: ${ssm:/serverless-websockets/wave-example-enabled}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - !GetAtt "DynamoDBChannelsTable.Arn"
        - !GetAtt "DynamoDBConnectionPoolTable.Arn"
    - Effect: Allow
      Action:
        - sqs:SendMessage
      Resource:
        - !GetAtt "SQSWebhookQueue.Arn"

functions:
  api:
    handler: handlers/api.php
    timeout: 28
    layers:
      - ${bref:layer.php-74-fpm}
    events:
      - httpApi: '*'
  websocket:
    handler: handlers/websocket.php
    layers:
      - ${bref:layer.php-74}
    events:
      - websocket: $connect
      - websocket: $disconnect
      - websocket:
          route: $default
          routeResponseSelectionExpression: $default
  webhook:
    handler: handlers/webhook.php
    layers:
      - ${bref:layer.php-74}
    timeout: 300
    reservedConcurrency: 10
    events:
      - sqs:
          arn: !GetAtt "SQSWebhookQueue.Arn"
          batchSize: 1

resources:
  Resources:
    # This table is used to have a reference to all connected clients and their assigned socket ID's
    DynamoDBConnectionPoolTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: serverless-websockets-connection-pool
        BillingMode: 'PAY_PER_REQUEST'
        AttributeDefinitions:
          - AttributeName: connection-id
            AttributeType: S
        KeySchema:
          - AttributeName: connection-id
            KeyType: HASH
    # This table is used to have a reference to all occupied channels and their connected clients and optional user info
    DynamoDBChannelsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: serverless-websockets-channels
        BillingMode: 'PAY_PER_REQUEST'
        AttributeDefinitions:
          - AttributeName: channel-id
            AttributeType: S
        KeySchema:
          - AttributeName: channel-id
            KeyType: HASH
    # This queue is used to asynchronously handle sending webhooks
    SQSWebhookQueue:
      Type: AWS::SQS::Queue
      Properties:
        # Wait this amount of time before allowing a message to become visible again to other workers
        VisibilityTimeout: 360
        # We retry up to 4 times this way although we should have HTTP failures be handled inside the Lambda
        # and try to never fail the execution so we don't hammer the webhook target with a large amount of events
        MessageRetentionPeriod: 1440

plugins:
  - ./vendor/bref/bref

package:
  exclude:
    - 'node_modules/**'
    - 'tests/**'
